name: "General"

on:
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: id11
        run: |
          echo "Hello world job 1"
  job2:
    if: contains(github.event.head_commit.message, '[include job2]') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - id: id22
        run: |
          echo "Hello world job 2"