name: "continuous integration and deployment"

on:
  push:
    branches-ignore:
      - 'main'
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'dev environment'
        required: true
        default: 'dev2'

env:
  SERVERR: TUAN_TRAN_CHILD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: id1
        run: |
          echo "Hello world job 1"
          echo ${{ env.SERVERR }}
          echo ${{ env.SERVER }}
  jfrogDeploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: contains('
      refs/heads/develop
      ', github.ref) || startsWith(github.ref, 'refs/tags/')
    steps:
      - id: id122
        run: |
          echo "Hello world job 2"
  buildImage:
    runs-on: ubuntu-latest
    needs: [build, jfrogDeploy]
    if: contains('
      refs/heads/develop
      ', github.ref) || startsWith(github.ref, 'refs/tags/')
    steps:
      - id: id122
        run: |
          echo "Hello world job 2"
  helmPackage:
    runs-on: ubuntu-latest
    needs: [build, buildImage]
    if: contains('
      refs/heads/develop
      ', github.ref) || startsWith(github.ref, 'refs/tags/')
    steps:
      - id: id122
        run: |
          echo "Hello world job 2"
  pushImageToACR:
    runs-on: ubuntu-latest
    needs: [build, helmPackage]
    if: contains('
      refs/heads/develop
      ', github.ref) || startsWith(github.ref, 'refs/tags/')
    steps:
      - id: id122
        run: |
          echo "Hello world job 2"
  deployToDev:
    runs-on: ubuntu-latest
    needs: [ build, helmPackage, pushImageToACR ]
    steps:
      - id: id1
        run: |
          echo "Hello world job 2"
  deployToBdd:
    runs-on: ubuntu-latest
    needs: [ build, helmPackage, pushImageToACR, deployToDev ]
    steps:
      - id: id1
        run: |
          echo "Hello world job 2"

  deployToDev2:
    if: contains(github.event.head_commit.message, '[include job2]') || (github.event_name == 'workflow_dispatch' || github.event.inputs == 'dev2')
    runs-on: ubuntu-latest
    needs: [ build, helmPackage, pushImageToACR ]
    steps:
      - id: id1
        run: |
          echo "Hello world job 2"

  deployToDev3:
    if: contains(github.event.head_commit.message, '[include job2]') || (github.event_name == 'workflow_dispatch' || github.event.inputs == 'dev2')
    runs-on: ubuntu-latest
    needs: [ build, helmPackage, pushImageToACR ]
    steps:
      - id: id1
        run: |
          echo "Hello world job 2"

  deployToDev4:
    if: contains(github.event.head_commit.message, '[include job2]') || (github.event_name == 'workflow_dispatch' || github.event.inputs == 'dev2')
    runs-on: ubuntu-latest
    needs: [ build, helmPackage, pushImageToACR ]
    steps:
      - id: id1
        run: |
          echo "Hello world job 2"