name: "continuous integration and deployment"

on:
  push:
    branches-ignore:
      - 'main'
    tags:
      - '*'
  workflow_dispatch:

env:
  SERVERR: TUAN_TRAN_CHILD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: id1
        run: |
          echo "Hello world job 1"
          echo ${{ env.SERVERR }}
          echo ${{ env.SERVER }}
  deployToDev:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - id: id1
        run: |
          echo "Hello world job 2"

  deployToDev2:
    if: contains(github.event.head_commit.message, '[include job2]') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - id: id1
        run: |
          echo "Hello world job 2"