name: "Manually"

on:
  workflow_dispatch:

jobs:
  job3:
    runs-on: ubuntu-latest
    steps:
      - id: id1
        run: |
          echo "Hello world job 1"
  job4:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - id: id1
        run: |
          echo "Hello world job 2"